### ISSUE TITLE
v2 Umbrella

### ISSUE THREAD

**Issue by joews** [joews/prequel#124]
* [x] TypeScript setup
* [ ] Rationalise AST: _working here_
* [ ] Simple WHERE execution
* [ ] Plan stage
* [ ] Full support for streaming iterables
* [ ] Aggregations
