### ISSUE TITLE
1.0.0 testing

### ISSUE THREAD

**Issue by joews** [joews/prequel#49]
1.0.0 is almost feature complete. Write some more integration (and some unit) tests to find more bugs.
## Tasks
- [x] Do not count integration test output in coverage - I want to get everything unit tested and integration coverage masks that.
## Tests
- [x] Unit test red paths in `query.js`
- [x] Unit test red paths in `enrich.js`
- [ ] Test queries that reserved words as identifiers
- [ ] Quoted field names
- Lots of integration tests
